const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "94766632281"
const SESSION_ID = "PRABATH-MD~BfVXwa7J#FvKcZD1RJqspCyQXHuFAJQqWz-JxxMEd3AVtOFV1kHM"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
